config/routes.rb
Rails.application.routes.draw do
  resources :members
  devise_for :users
  resources :products
  resources :orders

  root to: "products#index"
  
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  # post 'add_to_cart' => "products#add_to_cart"

  post 'products/remove_item/:id', to: 'products#remove_item', as: 'remove_item'
  # post 'products/add_to_cart/:id', to: 'products#add_to_cart'

  # post 'orders/new_order/:id', to: 'orders#new', as: 'new_order'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'checkout/create', to: 'checkout#create'

  post 'payments/checkout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :products
    has_one :user
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_many :orders
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify strict: true
  has_many :orders
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	
         after_create :assign_default_role
  
  def assign_default_role
    self.add_role(:newuser) if self.roles.blank?
  end

  after_create do
    result = Braintree::Customer.create(
      # :first_name => "Jen",
      # :last_name => "Smith",
      # :company => "Braintree",
      :email => email,
    )
    update(braintree_customer_id: result.customer.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        product = Product.find(params[:id])
        @session = Stripe::Checkout::Session.create({
          payment_method_types: ['card'],
          line_items: [{
              name: product.name,
              amount: product.price,
              currency: "usd",
              quantity: 1
          }],
          mode: 'payment',
          success_url: root_url,
          cancel_url: root_url,
        })
        respond_to do |format|
            format.js
        end
    end
end

app/controllers/members_controller.rb
class MembersController < Devise::RegistrationsController
  def index
    @users = User.all
end

private
def user_params
    params.require(resource).permit(:email, :password, :password_confirmation, :full_name)
end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    # u = User.find(:id)
    @orders = Order.all
    # @user = User.find(user_id)
    # @orders = Order.find(params[:id])
    # @orders = Order.current_scope
    # products = Product.all
  end

  def show
    # @orders = Order.find(params[:id])
    # u = User.find_by(:id)
    # respond_with User.find(params[:id])

    @order = current_user.orders
  end

  def new
    @orders = Order.new
  end

  def create
    # @ordars = Ordar.new
      # byebug
    @orders = Order.create(order_params)
    # @cart.quantity = params[:quantity]
    # @cart.products << Product.find(params[:product_id])

    # #@cart = Cart.create(cart_params)
    # @cart.save

    @cart = Product.find(session[:cart])
    # binding.pry
    @orders.products << @cart
    @orders.save

    session[:cart] = []
    
    redirect_to products_path
    # @ordar = Ordar.new(order_params)
    # @current_cart.line_items.each do |item|
    #   @order.line_items << item
    #   item.cart_id = nil
    # end
    # @order.save
    # Cart.destroy(session[:cart_id])
    # session[:cart_id] = nil
    # redirect_to root_path
  end

  def destroy
    @orders = Order.find(params[:id])
    @orders.destroy
    redirect_to orders_path
  end

  private
  # binding.pry
    def order_params
      params.require(:order).permit(:name, :email, :address, :user_id)
    end

    # def order_by_id
    #   u = User.find_by(id:3)
    #   u.orders
    # end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  def index
  end

  def new
    @client_token = gateway.client_token.generate
  end

  def checkout
    nonce_from_the_client = params[:payment_method_nonce]

    result = gateway.transaction.sale(
      :amount => price,
      :payment_method_nonce => nonce_from_the_client,
      :device_data => device_data_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
    )

    if result.success?
      puts "success!: #{result.transaction.id}"
    elsif result.transaction
      puts "Error processing transaction:"
      puts "  code: #{result.transaction.processor_response_code}"
      puts "  text: #{result.transaction.processor_response_text}"
    else
      p result.errors
    end

    begin
      customer = gateway.customer.create!(:first_name => "Josh")
      puts "Created customer #{customer.id}"
    rescue Braintree::ValidationsFailed
      puts "Validations failed"
    end
    
  end


  def gateway
    env = ENV["BT_ENVIRONMENT"]

    @gateway ||= Braintree::Gateway.new(
      :environment => env && env.to_sym,
      :merchant_id => ENV["BT_MERCHANT_ID"],
      :public_key => ENV["BT_PUBLIC_KEY"],
      :private_key => ENV["BT_PRIVATE_KEY"],
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :intilize_session
    before_action :load_cart
    
    def index
      @products = Product.all
    end
  
    def new
      @product = Product.new
    end
  
    def create
      @product = Product.create(product_params)
  
      respond_to do |format|
        if @product.save
          format.html { redirect_to products_path, notice: 'Product was successfully created.' }
          format.js
          format.json { render json: @product, status: :created, location: @product }
        else
          format.html { render action: "new" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product = Product.find(params[:id])
      @product.update(product_params)
      redirect_to products_path
    end
  
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      {notice: "Product deleted successfully" }
  
      respond_to do |format|
        format.html { redirect_to products_path}
        format.json { head :no_content }
        format.js   { render :layout => false }
     end
    end
  
    def add_to_cart
      param = params[:id]
      session[:cart] << param
      # if session[:cart].include?(param)
      #   flash.alert = "Already added."
      # end
      redirect_to products_path  
    end
  
    def remove_item
      param = params[:id]
      session[:cart].delete(param)
      redirect_to products_path
    end
    
    private
      def product_params
        params.require(:product).permit(:name, :price, :image)
      end
  
      def intilize_session
        # if session[:cart]
        #     @cart = session[:cart].find_by(:id => session[:cart])
          # if @cart.present?
        session[:cart] ||= []
      end
  
      def load_cart
        @cart = Product.find(session[:cart])
      end
  
        # end
      # end
  end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/checkout/create.js.erb
var stripe = Stripe("<%= Rails.application.credentials[:stripe][:public] %>");

  stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
  }).then(function (result) {
    
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopAppV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/header" %>

  <p class="notice" style="text-align: center;font-size:28px;"><%= notice %></p>
  <p class="alert" style="text-align: center; font-size:28px;"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h2>All Orders</h2>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
h2
{
  text-align: center;
}
</style>
<table>
  <tr>
    <td>Email</td>
    <td>Id</td>
  </tr>
  <% @users.each do |user| %>  
  
  <tr>
    <td><%= user.email %></td>
    <td><%= user.id %></td>
  </tr>
<% end %>
</table>

app/views/orders/index.html.erb
<h2>All Orders</h2>
<%= current_user.id %>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
h2
{
  text-align: center;
}
</style>
<table>
  <tr>
    <td>Email</td>
    <td>Name</td>
    <td>Address</td>
    <td>Product</td>
    <td>Price</td>
  </tr>
  <% Order.all.each do |order| %>  
  
  <tr>
    <td><%= order.email %></td>
    <td><%= order.name %></td>
    <td><%= order.address %></td>
    <% order.products.each do |product| %>
    <td><%= product.name %><br></td>
    <td><%= number_to_currency(product.price) %><br></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/orders/new.html.erb
<div class= "order-page">

<h2 style="text-align: center; margin-bottom:50px;"> Place Order </h2>

<%= form_for(@orders) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, autofocus: true %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email, value:current_user.email%>
    </p>
    <p>
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </p>

    <%= f.hidden_field :user_id, value:current_user.id %>
    
    <p>
      <%= f.submit %>
    </p>
  <% end %>
  </div>

app/views/orders/show.html.erb
<h2>All Orders</h2>
<%= current_user.id %>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
h2
{
  text-align: center;
}
</style>
<table>
  <tr>
    <td>Email</td>
    <td>Name</td>
    <td>Address</td>
    <td>Product</td>
    <td>Price</td>
  </tr>
  <% @order.each do |order| %>  
  <tr>
    <td><%= order.email %></td>
    <td><%= order.name %></td>
    <td><%= order.address %></td>
    <% order.products.each do |product| %>
    <td><%= product.name %><br></td>
    <td><%= number_to_currency(product.price) %><br></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/payments/checkout.html.erb
<h1>Payments#checkout</h1>
<p>Find me in app/views/payments/checkout.html.erb</p>

app/views/products/edit.html.erb
<%= form_for(@product) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
    </p>
    <p>
      <%= f.label :price %><br>
      <%= f.number_field :price, required: true %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>  

app/views/products/index.html.erb
<% if current_user.has_role? :newuser %>
<div id="mySidepanel" class="sidepanel" style="float: left:">
<details>
<% if @cart.empty? %>
<p> cart is empty <p>
<% else %>
<summary>Cart</summary>
  <% @cart.each do |p| %>
    <%=  p.name  %> | <%= link_to "Remove", remove_item_path(p), method: :post %> --
  <% end %>
  <%= link_to "Proceed to checkout", new_order_path(p) %>
<% end %>
</details>
</div>
<% end %> 
    
<div class="container">
    <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-6 col-lg-4 g-mb-30">
      <article class="u-shadow-v18 g-bg-white text-center rounded g-px-20 g-py-40 g-mb-5">
        <% if product.image.attached? %>
           <%= image_tag url_for(product.image), style: 'height:500px;width:300px;' %>
        <% end %>
        <h4 class="h5 g-color-black g-font-weight-600 g-mb-10"><%= product.name %></h4>
        <span class="d-block g-color-primary g-font-size-16"><%= number_to_currency(product.price/100) %></span>
        <% if current_user.has_role? :newuser %>
        <%= link_to "Add to cart", add_to_cart_path(product.id), method: :post, class: "btn"%>
        <%= product.sales_count %>
        <%= button_to "Buy Now!", checkout_create_path(id: product.id), remote: true, class: "btn"%>
        <% end %>
        <% if current_user.has_role? :admin %>
        <%= link_to "Edit", edit_product_path(product) %> |
        <%= link_to "Delete", product_path(product), {method: :delete, data: {confirm: "Are you sure?"}} %>
      <% end %>
      </article>
      </div>
    <% end %>
    </div>
</div>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>

    <div class="uk-container" style="width: 260px; margin: 0 auto;">
      <div uk-grid>		
          <div class="uk-width-1-2">
              <div class='uk-width-1-1@s'>
                  <h2 class="uk-text-center">Product Details</h2>
                  <hr />
                  <div class="uk-width-1-1@s">
                      <label class="uk-form-label" for="txtModel">Product Name</label>
                      <div class="uk-form-controls">
                          <p style= "width: auto;"><%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" , class: 'uk-input'%></p>
                      </div>
                  </div>

                  <div class="uk-width-1-1@s">
                      <label class="uk-form-label" for="txtModel">Product Image</label>
                      <div class="uk-form-controls">
                          <p style= "width: auto;"><%= f.file_field :image %></p>
                      </div>
                  </div>
                  
                  <div class="uk-margin">
                      <label class="uk-form-label" for="txtBrand">Price</label>
                      <div class="uk-form-controls">
                          <p><%= f.number_field :price, required: true, class: 'price', placeholder: "Enter product price" %></p>
                      </div>
                  </div>
                         <%= f.submit %>
  
              </div>
          </div>
      </div>
  </div>
  </div>
  <% end %>  
  

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <p class="navbar-brand">and_joy</p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div style = "padding-left: 700px;">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav text-center">
    <% if user_signed_in? %> 
    <% if current_user.has_role? :admin %>
      <li class="nav-item active">
        <%= link_to "Add New Product", new_product_path, class: 'nav-link sr-only' %>
      </li>
    <% end %>
      <li class="nav-item">
        <%= link_to "Home", products_path, class: 'nav-link' %>
      </li>
      <% if current_user.has_role? :newuser %>
      <li class="nav-item">
        <%= link_to "Orders", order_url(current_user.id), class: 'nav-link' %>
      </li>
      <% end %>
      <% if current_user.has_role? :admin %>
      <li class="nav-item">
        <%= link_to "Users", members_path ,class: 'nav-link' %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete ,class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>